- name: "Set allow-user-extension-install to '{{ boolean_value }}'"
  ansible.builtin.include_tasks: func/edit_bool_policy.yml
  vars:
    policy_name: "BlockExternalExtensions"
    boolean_value: "{{ not allow_user_ext_install }}"

