- name: "Set enable-cast-ext to '{{ boolean_value }}'"
  ansible.builtin.include_tasks: func/edit_bool_policy.yml
  vars:
    policy_name: "EnableMediaRouter"
    boolean_value: "{{ enable_builtin_cast_ext }}"
    locked: true

- name: "Set allow-user-extension-install to '{{ boolean_value }}'"
  ansible.builtin.include_tasks: func/edit_bool_policy.yml
  vars:
    policy_name: "BlockExternalExtensions"
    boolean_value: "{{ not allow_user_ext_install }}"
    locked: true

- name: "Set extension-install-blocklist to '{{ descrip_value }}'"
  ansible.builtin.include_tasks: func/edit_array_policy.yml
  vars:
    policy_name: "ExtensionInstallBlocklist"
    array_element_list: "{{ all_value if allow_user_ext_install else none_value }}"
    descrip_value: "{{ 'NONE' if allow_user_ext_install else 'ALL' }}"
    all_value: []
    none_value: ["*"]
    locked: true

