- name: "Set allow-user-extension-install to '{{ boolean_value }}'"
  ansible.builtin.include_tasks: func/edit_bool_policy.yml
  vars:
    policy_name: "BlockExternalExtensions"
    boolean_value: "{{ not allow_user_ext_install }}"
    locked: true

- name: "Set extension-install-blocklist to 'ALL'"
  ansible.builtin.include_tasks: func/edit_array_policy.yml
  vars:
    policy_name: "ExtensionInstallBlocklist"
    array_element_list: [ '*' ]
    locked: true
  when: not allow_user_ext_install

- name: "Set extension-install-blocklist to 'NONE'"
  ansible.builtin.include_tasks: func/edit_array_policy.yml
  vars:
    policy_name: "ExtensionInstallBlocklist"
    array_element_list: []
    locked: true
  when: allow_user_ext_install

