- name: "Set enable-search-in-url-bar to '{{ boolean_value }}'"
  ansible.builtin.include_tasks: func/edit_bool_policy.yml
  vars:
    policy_name: "DefaultSearchProviderEnabled"
    boolean_value: "{{ enable_search_in_url_bar }}"

- name: "Set default-search-provider-url to '{{ string_value }}'"
  ansible.builtin.include_tasks: func/edit_string_policy.yml
  vars:
    policy_name: "DefaultSearchProviderSearchURL"
    string_value: "{{ search_providers[0].search_url }}"

- name: "Set default-search-provider-name to '{{ string_value }}'"
  ansible.builtin.include_tasks: func/edit_string_policy.yml
  vars:
    policy_name: "DefaultSearchProviderName"
    string_value: "{{ search_providers[0].provider_name }}"

- name: "Set default-search-provider-hotkeys to '{{ string_value }}'"
  ansible.builtin.include_tasks: func/edit_string_policy.yml
  vars:
    policy_name: "DefaultSearchProviderKeyword"
    string_value: "{{ search_providers[0].hotkeys }}"

