- name: "Set show-search-suggestions-in-url-bar to '{{ boolean_value }}'"
  ansible.builtin.include_tasks: func/edit_bool_policy.yml
  vars:
    policy_name: "SearchSuggestEnabled"
    boolean_value: "{{ show_search_suggestions_in_url_bar }}"
    locked: true

- name: "Create default-search-url string as '{{ modified_search_string_url }}'"
  ansible.builtin.set_fact:
    default_search_url: "{{ modified_search_string_url }}"
  vars:
    modified_search_string_url: "{{ search_providers[0].search_url | replace('%s', '{searchTerms}') }}"

- name: "Set default-search-provider-url to '{{ string_value }}'"
  ansible.builtin.include_tasks: func/edit_string_policy.yml
  vars:
    policy_name: "DefaultSearchProviderSearchURL"
    string_value: "{{ default_search_url }}"

- name: "Set default-search-provider-suggest-url to '{{ string_value }}'"
  ansible.builtin.include_tasks: func/edit_string_policy.yml
  vars:
    policy_name: "DefaultSearchProviderSuggestURL"
    string_value: "{{ default_search_url }}"

- name: "Set default-search-provider-name to '{{ string_value }}'"
  ansible.builtin.include_tasks: func/edit_string_policy.yml
  vars:
    policy_name: "DefaultSearchProviderName"
    string_value: "{{ search_providers[0].provider_name }}"

- name: "Set default-search-provider-hotkeys to '{{ string_value }}'"
  ansible.builtin.include_tasks: func/edit_string_policy.yml
  vars:
    policy_name: "DefaultSearchProviderKeyword"
    string_value: "{{ search_providers[0].hotkeys }}"

