# block sites from displaying desktop notifications (if false, ask each time)
chromium_block_desktop_notfications: true

# block sites from displaying pop-ups (if false, always allow)
chromium_block_pop_ups: true

# save and auto-fill postal addresses that user enters into web forms
chromium_auto_fill_postal_addresses: true

# save and auto-fill credit card data that user enters into web forms
chromium_auto_fill_credit_card_data: false

# save and auto-fill site passwords
chromium_auto_fill_passwords: false

# use Chromium-builtin DNS client (if false, use OS's DNS client)
chromium_use_builtin_dns_client: false

# enable https-only-mode for browsing, and warn for http pages
chromium_enable_https_only_mode: true

# use Chromium-builtin DNS client (if false, use OS's DNS client)
chromium_use_dns_over_https: false

# check if Chromium is the default OS browser
chromium_check_if_default_browser: false

# report browser usage and crash-reporting data to Google
chromium_enable_browser_metrics_reporting: false

