- name: "Set Chromium policy '{{ policy_name }}' to {{ policy_value }}"
  ansible.builtin.lineinfile:
    path: "{{ locked_config_file_path if locked else overridable_config_file_path }}"
    regexp: >-
      ^  "{{ policy_name }}":
    insertafter: >-
      ^\{$
    line: "  \"{{ policy_name }}\": {{ policy_value }}{{ last_entry | ternary('', ',') }}"
    state: present
    create: no
  vars:
    locked: false
    last_entry: false
  become: true
  become_user: root

