# NOTE: To find extension ID, install the ext, enable developer mode,
#       and then go to chrome://extensions.
# Also see https://www.chromium.org/administrators/policy-list-3#ExtensionInstallForcelist

- name: "Initialize local policy-setting-var to assemble extension IDs"
  ansible.builtin.set_fact:
    chromium_extension_ids: []

- name: "Install https-everywhere extension via policy: {{ chromium_install_https_everywhere_ext }}"
  ansible.builtin.set_fact:
    chromium_extension_ids: "{{ chromium_extension_ids + [ 'gcbommkclmclpchllfjekcdonpmejbdp' ] }}"
  when: chromium_install_https_everywhere_ext

- name: "Install ublock-origin extension via policy: {{ chromium_install_ublock_origin_ext }}"
  ansible.builtin.set_fact:
    chromium_extension_ids: "{{ chromium_extension_ids + [ 'cjpalhdlnbpafiamejdnhcphjbkeiagm' ] }}"
  when: chromium_install_ublock_origin_ext

- name: "Install vimium extension via policy: {{ chromium_install_vimium_ext }}"
  ansible.builtin.set_fact:
    chromium_extension_ids: "{{ chromium_extension_ids + [ 'dbepggeogbaibhgnhhndojpepiihcmeb' ] }}"
  when: chromium_install_vimium_ext

- name: "Install bitwarden extension via policy: {{ chromium_install_bitwarden_ext }}"
  ansible.builtin.set_fact:
    chromium_extension_ids: "{{ chromium_extension_ids + [ 'nngceckbapebfimnlniiiahkandclblb' ] }}"
  when: chromium_install_bitwarden_ext

- name: "Install user-agent-switcher extension via policy: {{ chromium_install_user_agent_switcher_ext }}"
  ansible.builtin.set_fact:
    chromium_extension_ids: "{{ chromium_extension_ids + [ 'bhchdcejhohfmigjafbampogmaanbfkg' ] }}"
  when: chromium_install_user_agent_switcher_ext

