- name: "Initialize local policy-setting-var to assemble extension IDs"
  ansible.builtin.set_fact:
    extension_ids: []

- name: "Add enabled extension IDs to list"
  ansible.builtin.include_tasks: extension_ids.yml

- name: "Configure the vimium extension"
  ansible.builtin.include_role:
    name: ans_role_config_vimium
  vars:
    vimium_search_providers: "{{ chromium_search_providers }}"
    vimium_config_file_path: "{{ os_vimium_config_file_path }}"
    vimium_home_page: "{{ home_page }}"
  when: install_vimium_ext

- name: "Add policy setting used to install extensions via extension IDs"
  ansible.builtin.include_tasks: func/edit_array_policy.yml
  vars:
    policy_name: "ExtensionInstallForcelist"
    array_element_list: "{{ extension_ids }}"
    locked: true

