- name: "Run all role tasks for Ubuntu"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    os_overridable_config_file_path: "{{ ubuntu_overridable_config_file_path }}"
    os_locked_config_file_path: "{{ ubuntu_locked_config_file_path }}"
    os_vimium_config_file_path: "{{ ubuntu_vimium_config_file_path }}"
    os_chromium_main_cmd: "{{ linux_chromium_main_cmd }}"
  when: ansible_distribution == "Ubuntu"

- name: "Run all role tasks for Generic Linux OS"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    os_overridable_config_file_path: "{{ linux_overridable_config_file_path }}"
    os_locked_config_file_path: "{{ linux_locked_config_file_path }}"
    os_vimium_config_file_path: "{{ linux_vimium_config_file_path }}"
    os_chromium_main_cmd: "{{ linux_chromium_main_cmd }}"
  when: (ansible_system == "Linux") and (ansible_distribution != "Ubuntu")

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    os_overridable_config_file_path: "{{ freebsd_overridable_config_file_path }}"
    os_locked_config_file_path: "{{ freebsd_locked_config_file_path }}"
    os_vimium_config_file_path: "{{ freebsd_vimium_config_file_path }}"
    os_chromium_main_cmd: "{{ freebsd_chromium_main_cmd }}"
  when: ansible_os_family == "FreeBSD"

