- name: "Install main Chromium application"
  ansible.builtin.include_tasks: install/main.yml

- name: "Add optional Chromium extensions"
  ansible.builtin.include_tasks: extensions/main.yml

- name: "Setup 'locked' (aka 'managed') Chromium policies"
  ansible.builtin.include_tasks: locked_policies/main.yml

- name: "Setup 'overridable' (aka 'recommended') Chromium policies"
  ansible.builtin.include_tasks: overridable_policies/main.yml

- name: "Export Chromium command vars"
  ansible.builtin.include_tasks: export_vars/main.yml

