- name: "Create the locked config dir, at {{ chromium_os_locked_config_file_path | dirname }}"
  ansible.builtin.file:
    path: "{{ chromium_os_locked_config_file_path | dirname }}"
    state: directory
    owner: 'root'
    mode: '755'
  become: true
  become_user: root

- name: "Configure all settings in locked config file, at '{{ chromium_os_locked_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ chromium_os_locked_config_file_path }}"
    src: 'locked_policies.j2'
    owner: 'root'
    mode: '644'
    force: true
  become: true
  become_user: root

