- name: "Create the locked config dir, at {{ os_locked_config_file_path | dirname }}"
  ansible.builtin.file:
    path: "{{ os_locked_config_file_path | dirname }}"
    state: directory
    owner: 'root'
    mode: '755'
  become: true
  become_user: root

- name: "Add initial locked config file, at '{{ os_locked_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ os_locked_config_file_path }}"
    src: 'locked_policies.j2'
    owner: 'root'
    mode: '644'
    force: yes
  become: true
  become_user: root

