# SEE CHROMIUM PROJECT NOTES:
#   https://www.chromium.org/administrators/linux-quick-start

# chromium linux config (aka 'Policy') file, system-wide and overridable
overridable_config_file_path: '/etc/chromium/policies/managed/ansible_policies.json'

# chromium linux config (aka 'Policy') file, system-wide and locked
locked_config_file_path: '/etc/chromium/policies/recommended/ansible_policies.json'

