# block sites from displaying desktop notifications (if false, ask each time)
block_desktop_notfications: true

# block sites from displaying pop-ups (if false, always allow)
block_pop_ups: true

# save and auto-fill postal addresses that user enters into web forms
auto_fill_postal_addresses: true

# save and auto-fill credit card data that user enters into web forms
auto_fill_credit_card_data: false

# show "browser labs" features icon in toolbar
show_browser_labs_features: false

