- name: "Create the main Chromium config dir, at {{ os_chromium_config_dir }}"
  ansible.builtin.file:
    path: "{{ os_chromium_config_dir }}"
    state: directory
    owner: 'root'
    mode: '755'
  become: true
  become_user: root

